---
title: "What is cumulative achievement compared to quarterly targets?"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
params:
  selected_indicator: selected_indicator
  selected_ou: selected_ou
  selected_agency: selected_agency
  selected_type: selected_type
---

```{r debug, echo=FALSE, message=FALSE}
# 
library(tidyverse)
library(extrafont)
# library(gagglr)
# library(glue)
# library(scales)
# library(stringr)
# library(ggtext)
# library(tidytext)
# library(cowplot)
# library(janitor)
# #
# # Example Parameters for debugging purposes
# #
# selected_ou <- "South Sudan"
# selected_indicator <- "TX_CURR"
# selected_agency <- "All"
# selected_type <- "Total"
# #
# si_path() %>%
#   return_latest("MER_Structured_Datasets_OU_IM")
# 
# template_list <- list.files(path = here::here("POART_o_matic/templates"),
#                             full.names = FALSE,
#                             pattern = "pptx")
# #
# # # This assumes the user has their MSD path setup correctly and that they have
# # # at least one OU by IM file in that folder, this can be generalized
# # # to use different datasets but it works at the highest level of detail MSD
# #
# df_ou <- si_path() %>%
#   return_latest("MER_Structured_Datasets_OU_IM") %>%
#   read_msd()
# #
# # # this seems to only work interactively since I wasn't able to use
# # # the returned metadata object within the function when it was called from the app
# # metadata
# si_path() %>%
#   return_latest("MER_Structured_Datasets_OU_IM") %>%
#   get_metadata()

```

```{r global_vars, echo=FALSE, message=FALSE}

ref_id <- "4c86a407"

ou_achv_cumul <- function(.path, .indicator, .ou, 
                          .type, .title, .funding_agency, ...) {
  
  df_ou <- si_path() %>%
    return_latest(.path) %>%
    read_msd()
  
  curr_pd <- as.character(source_info(si_path() %>% 
                                        return_latest("MER_Structured_Datasets_OU_IM"),
                         return = "period"))
  
  curr_fy_lab <- as.character(source_info(si_path() %>%
                                            return_latest("MER_Structured_Datasets_OU_IM"),
            return = "fiscal_year_label"))
  
  qtrs_to_keep <- curr_pd %>%
    convert_qtr_to_date() %>%
    seq.Date(by = "-3 months", length = 6) %>%
    convert_date_to_qtr()
  
  # filter for type, Total or Adults/Children
  {if (.type == "Total") {
    
    df_ou <- df_ou %>%
      filter(
        indicator %in% .indicator,
        operatingunit == .ou) %>%
      resolve_knownissues() %>%
      pluck_totals()
  
  }
  else {
    
    peds <- c("<01", "01-04", "05-09", "10-14")
    adults <- c(
      "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49",
      "50-54", "55-59", "60-64", "65+")
    
    df_ou <- df_ou %>%
      filter(
        indicator %in% .indicator,
        operatingunit %in% .ou,
        (standardizeddisaggregate == "Age/Sex/HIVStatus" & ageasentered %in% peds) |
          (standardizeddisaggregate == "Total Numerator") |
          (standardizeddisaggregate == "Age/Sex/HIVStatus" & ageasentered %in% adults)) %>%
      resolve_knownissues() %>%
      mutate(type = case_when(
        standardizeddisaggregate == "Total Numerator" ~ "Total",
        standardizeddisaggregate == "Age/Sex/HIVStatus" &
          ageasentered %in% adults ~ "Adults (15+)",
        standardizeddisaggregate == "Age/Sex/HIVStatus" &
          ageasentered %in% peds ~ "Children (<15)")) %>%
      filter(type %in% .type)

  }}
  
  {if (.funding_agency != as.list("All")) {
    
    df_ou <- df_ou %>%
    filter(funding_agency == as.list(.funding_agency))
    
  }}
 
    df_final <- df_ou %>%
    resolve_knownissues() %>%
    group_by(operatingunit, indicator, fiscal_year) %>%
    summarise(across(c(starts_with("qtr"), cumulative, targets),
                     sum,
                     na.rm = TRUE), .groups = "keep") %>%
    reshape_msd(direction = "quarters") %>%
    adorn_achievement() %>%
    arrange(period) %>%
    mutate(
      period_num = as.numeric(str_sub(period, -1)),
      qtr_target = targets / ((4 - period_num) + 1),
      fiscal_year2 = str_extract(period, "FY[1-2][0-9]"),
      results_lab = case_when(period == curr_pd |
                                fiscal_year2 == curr_fy_lab ~
                                glue("{comma(results_cumulative)}")),
      achv_pct_label = case_when(period == curr_pd |
                                   fiscal_year2 == curr_fy_lab ~
                                   glue("{percent(achievement_qtrly)}")),
      ind_period = str_c(indicator, period, sep = "_")) %>%
    filter(period %in% qtrs_to_keep)
  
  df_final %>%
    ggplot(aes(x = period)) +
    geom_col(aes(y = qtr_target),
             alpha = .7, fill = usaid_lightgrey,
             position = position_dodge(width = .65)) +
    geom_col(aes(y = results_cumulative),
             alpha = .7, fill = scooter_med,
             position = position_dodge(width = .65)) +
    geom_text(aes(label = achv_pct_label, y = 0),
              position = position_dodge(width = 0.75), color = "#FFFFFF",
              family = "Source Sans Pro", size = 12 / .pt,
              vjust = -.5, na.rm = TRUE) +
    geom_text(aes(label = results_lab, y = results_cumulative),
              position = position_dodge(width = 0.75), color = scooter_med,
              family = "Source Sans Pro", size = 12 / .pt,
              vjust = -.5, na.rm = TRUE) +
    scale_x_discrete(breaks = unique(df_final$period)[grep("Q(2|4)", unique(df_final$period))]) +
    # how to dynamically add just a little excess to the
    # max. value to accommodate the geom_text?
    scale_y_continuous(
      limits = c(0, max(df_final$qtr_target) + 5000),
      label = label_number(scale_cut = cut_short_scale())) +
    labs(
      x = NULL, y = NULL, fill = NULL,
      title = glue("{.title}"),
      subtitle = glue("Cumulative Results and Quarterly Achievement (%) labeled for previous 4 quarters"),
      caption = glue("Source: {curr_pd} MSD | Ref id: {ref_id} | US Agency for International Development")) +
    si_style_yline() +
    theme(
      panel.spacing = unit(.5, "line"),
      legend.position = "none",
      plot.title = element_markdown(),
      strip.text = element_markdown()
    )

}

```

```{r viz, echo=FALSE, message=FALSE}

cumul_achv <- ou_achv_cumul(
      .path = "MER_Structured_Datasets_OU_IM",
      .indicator = selected_indicator,
      .ou = selected_ou,
      .title = "",
      .funding_agency = selected_agency,
      .type = selected_type
      )

cumul_achv

```